server:
  port: 8085
spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: book_user
    password: book_password

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
    api-url: https://api.telegram.org
